[package]
name = "boron"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "bvm"
path = "src/bvm.rs"

[[bin]]
name = "bassm"
path = "src/bassm.rs"